### PR TITLE
make raw cache data accessible.

### PR DESCRIPTION
**Pull request by yudai09**
I want to access raw hash data so that serialize it and store into a file.

### CODE REVIEW

**Comment by yudai09** [comment]
The license should be GPL.

**Comment by Seberius** [comment]
Hello,
Thank you for your interest in contributing to the library. I will leave it up to @SamSaffron to decide whether or not to accept this feature. I would wait to see what that decision is before working on my suggestions below.

The pull request will need to be revised as it is incomplete for a new method.  You will need to add:
- [ ] **TTL cache support** - Attempts are made to keep the methods between the LRU and TTL cache equivalent where possible.  Note that while the methods need to be named the same, the instance variables are named differently.  You will also need to consider how to handle the TTL cache.
- [ ] **ThreadSafe support** - Please refer to `lib/lru_redux/util/safe_sync.rb` for examples. You may also need to add support to `lib/lru_redux/util/safe_sync_jruby.rb` if tests fail (JRuby) without it.
- [ ] **Test coverage** - Appropriate tests should be added.  The tests should demonstrate that both the read and write have expected results.  Please refer to `test/cache_test.rb` for examples.

**Comment by SamSaffron** [comment]
Agree with all @Seberius in addition, this change feels a bit too wide to be allowed, instead supporting a to_json and from json or stuff like that feels more like the correct level of abstraction.

**Comment by yudai09** [comment]
I'm sorry. 
I overlooked to_a().
It's enough for my usage.

**Pull request closed without merging**
