### PR TITLE
Expiring cache

### PR DESCRIPTION
**Pull request by DylanGriffith**
We liked your gem and we needed expiration so I've added this. If you like it you can merge it. I'll totally understand, though, if you think it is out of scope for your gem.

### CODE REVIEW

**Comment by Seberius** [comment]
Hello,
I have a implementation I would like to propose as an expiring/TTL cache for the library.  The implementation is similar to what @DylanGriffith suggests near the end of his last reply.  You can see the implementation here: https://github.com/Seberius/cache_lib/blob/master/lib/cache_lib/ttl/cache.rb

I would like to address how the proposed implementation handles some of the issues @SamSaffron  raised.
> This implementation is only evicting keys on access, so potentially you can have large amount of keys still retained after the expiry date.

A separate ordered list of time values is stored (TTL list).  On access, the TTL list is iterated over from the oldest value until a 'live' value is found, evicting expired entries as it goes.  The advantage is that you always are only storing 'live' values when access completes and LRU eviction will never drop a 'live' value over an expired one.

> General pattern would be to add a bg thread to purge out keys (which should probably be an option)

A method called `#expire` is provided that will trigger a TTL eviction (the same that occurs on access).  This, I believe, could be accessed by a thread to provide the functionality described (I don't have very much experience with cron-like jobs in Ruby).

A couple additional notes about the implementation.
- The cache functions identically to the LRU cache, but with time functions (or exactly alike, if you set the ttl to `:none`).
- The ttl eviction time is determined at eviction.  That is, the cache stores entry times, not eviction times.  The advantage of this is that if you change the ttl on a live cache, the currently stored values will be evicted under the new ttl, not the one they were entered under.

If you are interested in that implementation, I have a question regarding pre-1.9 support.  Is support for Ruby 1.8 on a new cache wanted?  It can be implemented fairly efficiently (double doubly-linked list!), but will require a bit of extra work write and increases the support overhead.

Thanks!

**Comment by SamSaffron** [comment]
I really like this implementation, let's pull it in. 

Can you add some tests for it and bring it in? 

I do not think we need to worry about 1.8 here, 1.8 is mostly dead now.

**Comment by Seberius** [comment]
Sure, I will pull over the tests from the linked example.  I will need to add Timecop as a development dependency for TTL testing.

I would like to do it as two pull requests.  The first will be a performance improvement (`#shift` is much faster in Ruby 2.1+), some refactoring (e.g. changing ThreadSafeCache to use a mixin), and some very minor fixes.  The second would be the TTL cache implementation + tests + docs.

**Comment by SamSaffron** [comment]
@Seberius  also I have given push access to you for this repo just in case you need it. (we should still do PRs for these bigger changes though)

**Comment by DylanGriffith** [comment]
Looks like this is no longer needed.

**Pull request closed without merging**
